development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: budget247_prod
  pool: 5
  username: root
  password: slwfjrjs123

#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000

production:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000


test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pfm_test
  pool: 5
  username: root
  password: slwfjrjs123
  socket: <%= ['/var/lib/mysql/mysql.sock', '/var/run/mysqld/mysqld.sock', '/tmp/mysql.sock'].detect{ |socket| File.exist?(socket) } %>

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: budget247_prod
  pool: 5
  username: budget247_prod
  password: Aeraegee7DiP8ved1uh5
  socket: <%= ['/var/lib/mysql/mysql.sock', '/var/run/mysqld/mysqld.sock', '/tmp/mysql.sock'].detect{ |socket| File.exist?(socket) } %>
